name: ${project.name}
version: ${project.version}
main: me.fsml.holodrops.Main
api-version: 1.13
authors: [fsml]
description: ${project.description}
website: ${project.url}
commands:
  hdreload:
    usage: /<command>
    description: reloads the config
    permission: holodrops.reload
    aliases: [hdr]