name: ${project.name}
version: ${project.version}
main: me.fsml.holodrops.Main
api-version: 1.13
authors: [fsml]
description: ${project.description}
website: ${project.url}
commands:
  hdreload:
    usage: /<command>
    description: Reload the config
    permission: holodrops.reload
    permission-message: "§4§lHoloDrops | §r§cRequired permission: <permission>"
    aliases: [hdr]
permissions:
  holodrops.reload:
    description: Allows the ability to reload the config
    default: op